name: Deploy AI News Service to Cloud Run
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/113214288365/locations/global/workloadIdentityPools/github-provider/providers/github-provider'
          service_account: 'github-actions-deployer@dml2025rt.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ai-news-service
          source: ./ai-news-service
          region: us-central1 # You can change this if needed
          
      - name: Show Service URL
        run: 'echo "Service URL: ${{ steps.deploy.outputs.url }}"'